// APP_CHECK_AUTH
export const APP_CHECK_AUTH = "APP_CHECK_AUTH";
export const APP_CHECK_AUTH_SUCCESS = "APP_CHECK_AUTH_SUCCESS";

// APP_INIT
export const APP_INIT = "APP_INIT";
export const APP_INIT_SUCCESS = "APP_INIT_SUCCESS";
