import React from "react";
import classNames from "classnames/bind";
import { Inter } from "next/font/google";
import Head from "next/head";
import PropTypes from "prop-types";

import Icons from "@/public/icons/Icons";
import axiosServer from "@/utils/axioServer";

import { PageProps } from "./props";

import styles from "./Home.module.scss";

const inter = Inter({ subsets: ["latin"] });
const cx = classNames.bind(styles);

export default function Home(props = PageProps) {
  const { isAppInitialized } = props;
  console.log(
    "🚀 ~ file: Home.jsx:17 ~ Home ~ isAppInitialized:",
    isAppInitialized
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cx("main", inter.className)}>
        <div className={cx("description")}>
          <p>
            Get started by editing&nbsp;
            <code className={cx("code")}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <Icons.Vercel />
            </a>
          </div>
        </div>

        <div className={cx("center")}>
          <Icons.Next />
        </div>

        <div className={cx("grid")}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx("card")}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx("card")}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx("card")}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={cx("card")}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

Home.propTypes = {
  isAppInitialized: PropTypes.bool,
};

export async function getServerSideProps() {
  // EX: this is for server side rendering
  const data = await axiosServer.get(
    "https://api.github.com/repos/vercel/next.js"
  );

  return {
    props: {
      data,
    },
  };
}

Home.defaultProps = PageProps;
